### ISSUE TITLE
Question/Help: RHEL_RELEASE_CODE is not defined 

### ISSUE THREAD

**Issue by chilicat** [LIS/lis-rpm-build-pipeline#59]
Hallo,

I try to build the LIS package myself since we need it for a custom kernel.
I'm not experienced in Kernel module building, I apology for the possible newbie question.

To build the project I use the LS rpm source package downloaded from here: https://aka.ms/lis 

One of the first error messages I get is "RHEL_RELEASE_CODE is not defined "
Do I miss something obvious? Do I have to define parameter?

```
rpmbuild -ba -D "kernel_version $(uname -r)" lis-rhel7.spec 

n file included from /root/rpmbuild/BUILD/hv/obj/default/arch/x86/hyperv/hv_init.c:21:0:
/root/rpmbuild/BUILD/hv/obj/default/arch/x86/include/uapi/lis/asm/hyperv.h:159:5: warning: "RHEL_RELEASE_CODE" is not defined [-Wundef]
 #if(RHEL_RELEASE_CODE <= RHEL_RELEASE_VERSION(7,0))
```

thank you for your help.

**Comment by santoshx** [comment]
The sources packed in this rpm comes from github.com/lis/lis-next
These sources are applicable only for RHEL version <= 7.6 and its derivatives (Centos, Oracle Linux).
In case you are using latest kernel version from kernel.org, LIS already included there. You don't need this.

**Comment by chilicat** [comment]
Thanks.

**Comment by chilicat** [comment]
Yes. The driver are loaded, on a second look. My remaining issue is that ethtools does not show any information. 
Thanks for the response.
